### ISSUE TITLE
TODO: 도전 요구 사항

### ISSUE THREAD

**Issue by donkim1212** [donkim1212/ch3-2-item-simulator#10]
---------------------------------------- 아래부터는 도전 요구 사항

**shops**
 아이템 구입 (인증 필요)
 - [x] 캐릭터의 ID는 URI 파라미터로, 구매할 아이템의 코드와 수량을 request
 - [x] 성공 시 잔액 반환, 아이템은 인벤토리로

 아이템 판매 (인증 필요)
 - [x] 원가의 60%로 판매
 - [x] 인벤토리에 있는 아이템만 판매 가능 (장착된 아이템은 무시)
 - [x] 성공 시 잔액 반환

**inventories**
 보유 아이템 모두 조회 (인증 필요)
 - [x] 캐릭터 ID는 URI 파라미터로
 - [x] 아이템 코드, 이름, 수량을 담은 객체 배열 반환

**equipments**
 장착 아이템 조회
 - [x] 캐릭터 ID는 URI 파라미터로
 - [x] 장착한 아이템의 코드와 이름을 담은 객체 배열 반환 (아무것도 장착하지 않은 경우 빈 배열 반환)

 아이템 장착/탈착 (인증 필요)
 - [x] 캐릭터 ID는 URI 파라미터로
 - [x] 아이템 코드는 request에서 전달 받기
 
**works**
 게임머니 벌기
 - [x] 캐릭터 ID를 URI로 받기
 - [x] 호출할 때 마다 100원을 번다
 - [x] 잔액을 반환
