### ISSUE TITLE
TODO: project initial setup

### ISSUE THREAD

**Issue by donkim1212** [donkim1212/ch3-2-item-simulator#3]
- [ ] 이전 과제 기반으로 프로젝트 구조 setup
- [ ] ERD 작성하기
- [ ] MongoDB와 mongoose를 빼고 MySQL(AWS RDS)과 Prisma로 전환하기
- [ ] API 명세서 작성하기
- [ ] 명세서에 따라 필요한 라우터 및 해당하는 CRUD 기능의 기본 틀 추가하기
- [ ] 각 기능의 요구 사항에 따라 validator 및 authenticator 미들웨어 생성 및 추가하기
