### ISSUE TITLE
TODO: 필수 요구 사항

### ISSUE THREAD

**Issue by donkim1212** [donkim1212/ch3-2-item-simulator#8]
**users**
 회원 가입
 - [x] 아이디: 영어 소문자 및 숫자
 - [x] 비밀번호 6자 이상
 - [x] 비밀번호 확인: 비밀번호와 일치
 - [x] 성공 시 비밀번호 제외 정보 반환

 로그인
 - [x] 아이디, 비밀번호 요구
 - [x] 성공 시 accessToken 반환 (로그인 계정 ID 담아야 함)

**characters**
 생성 (인증 필요)
 - [x] 기본 게임 머니 1만

 삭제 (인증 필요)
 - [x] 내 계정 캐릭터가 아니라면 삭제 불가

 조회
 - [x] 내 캐릭터인 경우 게임머니까지 조회

**items**
 생성
 - [x] 아이템 능력 (JSON으로) 및 가격 전달받기
 
 수정
 - [x] 가격은 수정 불가 하도록

 모든 아이템 목록 조회
 - [x] 코드, 이름, 가격만 조회

 단일 아이템 조회
 - [x] 코드, 이름, 능력, 가격 조회
